"""
Base tactic module interface.

All tactics inherit from TacticModule and implement the required methods.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import TYPE_CHECKING, Optional

from ares.behaviors.combat_individual_behavior import CombatIndividualBehavior
from sc2.unit import Unit

if TYPE_CHECKING:
    from ManifestorBot.manifestor_bot import ManifestorBot
    from ManifestorBot.manifests.heuristics import HeuristicState
    from ManifestorBot.manifests.strategy import Strategy


@dataclass
class TacticIdea:
    """
    A tactic idea generated by a unit.
    
    This is what flows through the suppression logic before being
    converted into an actual behavior.
    """
    tactic_module: 'TacticModule'
    confidence: float           # 0.0 to 1.0 - how good is this idea
    evidence: dict              # What triggered this idea (for debugging)
    target: Optional[object] = None  # Target unit, position, or None
    
    
class TacticModule(ABC):
    """
    Base class for all tactic modules.
    
    Each tactic is a self-contained module that knows:
    1. When it is applicable (is_applicable)
    2. How to generate an idea (generate_idea)
    3. How to execute via Ares behaviors (create_behavior)
    """
    
    def __init__(self):
        self.name: str = self.__class__.__name__
        
    @abstractmethod
    def is_applicable(self, unit: Unit, bot: 'ManifestorBot') -> bool:
        """
        Can this tactic even be considered for this unit right now?
        
        This is a fast filter - return False immediately if the tactic
        can't possibly apply (wrong unit type, no valid targets, etc).
        """
        pass
        
    @abstractmethod
    def generate_idea(
        self,
        unit: Unit,
        bot: 'ManifestorBot',
        heuristics: 'HeuristicState',
        current_strategy: 'Strategy'
    ) -> Optional[TacticIdea]:
        """
        Generate a tactic idea for this unit if appropriate.
        
        Returns None if this tactic doesn't make sense right now,
        or a TacticIdea with a confidence score if it does.
        
        The confidence score should be built from multiple sub-signals,
        not just pulled out of thin air.
        """
        pass
        
    @abstractmethod
    def create_behavior(
        self,
        unit: Unit,
        idea: TacticIdea,
        bot: 'ManifestorBot'
    ) -> Optional[CombatIndividualBehavior]:
        """
        Convert an approved idea into an Ares behavior for execution.
        
        This is where the tactic actually becomes real commands.
        Return None if the idea can't be executed for some reason.
        """
        pass
